# 📚 GAME CONTENT LIBRARY (PHASE 19 - EXPANDED)

GAME_DATA = {
    "tod_truth": [
        # --- ICEBREAKERS ---
        "What is the last lie you told?", 
        "What is your biggest fear?",
        "Who is your secret crush?",
        "What is your most embarrassing moment?", 
        "Have you ever cheated on a test?",
        "What is the worst gift you ever received?", 
        "What is your biggest regret?",
        "When was the last time you cried?", 
        "What is a secret you've never told anyone?",
        "If you could switch lives with one person, who would it be?",
        "What is a habit you want to break?", 
        "Who is the most annoying person you know?",
        "What is your biggest insecurity?",
        "What is the weirdest dream you've ever had?",
        "Have you ever stalked someone on social media?",
	    "Do you have any fake account?",
        "What is the pettiest thing you have ever done?",
        "If you were invisible for a day, what would you do?",
        "What is the worst date you've ever been on?",
        "Have you(someone) ever ghosted someone(you)?",
        "What is one thing you wish you could change about yourself?",
        "Who is the last person you searched on Instagram?",
        "Have you ever broken the law?",
        "What is the most expensive thing you've bought and regretted?",
        "If you had to marry the last person you texted, who would it be?",
        "What is your guilty pleasure?",
        
        # --- DEEP / VIBE CHECK ---
        "Do you believe in soulmates?",
        "What is your biggest deal-breaker in a relationship?",
        "Would you forgive a cheater?",
        "What is the happiest memory of your childhood?",
        "Do you think you are a good person?",
        "What is one thing you want to achieve before you die?",
        "Do you believe in ghosts or aliens?",
	    "Saddest moment of your life?",
        "What is the hardest lesson you've had to learn?",
        "If you could apologize to one person from your past, who would it be?",
        "Are you happy with where you are in life right now?",
        "What is your definition of love?",
        "Have you ever fallen in love with a friend?",
        "What is something you are sensitive about?",
        "Do you trust people easily?",
        "What is your biggest fear about the future?",
        # --- FLIRTY & SPICY (User Added) ---
        "What is your love language?",
        "What is your biggest fantasy?",
        "What is one thing you struggle with in relationships?",
        "What was your first impression of me (based on this chat)?",
        "What is the first thing that attracts you to someone?",
        "What usually gets you in a romantic mood?",
        "Have you ever turned down a sexual opportunity and regretted it?",
        "Have you ever hooked up with someone you regret?",
        "At what age did you first learn about sex?",
        "Have you ever sexted?",
        "What is the sexiest song you've ever heard?",
        "What is the sexiest movie scene you've ever watched?",
        "At what age did you watch your first adult video?",
        "Have you ever hit on a random attractive stranger?",
        "Have you ever tried to get back together with an ex?",
        "What is a romantic act that you think is overrated?",
        "What romantic activity do you think is underrated?",
        "Can you fall asleep while cuddling/kissing?",
        "Kissing on the first date: Yay or Nay?",
        "Public Displays of Affection (PDA): Yay or Nay?",
        "What is your favorite body part to be kissed?",
        "Where do you like to leave/get a hickey?",
        "What is the sexiest outfit someone can wear?",
        "How old were you when you had your first kiss?",
        "What do you think is the sexiest part of the opposite gender's body?",
        "What do you think is the sexiest part of YOUR body?"
    ],

    "tod_dare": [
        # --- DIGITAL DARES (Safe for Chat) ---
        "Send a voice note singing 'Happy Birthday' to me.", 
        "Send the last photo which you took (no cheating!).",
        "Send me picture of your nose",
		"Show me your Nails", 
        "Send a sticker that describes your mood right now.",
        "Send me voice note of Count 10 to 1 (quickest you can!)",
        "Send me 5 last used Emoji", 
		"Send a voice note blowing a kiss.",
        "Send a photo of just your lips.",
        "Describe your ideal first date in detail.",
        "Send a voice note whispering 'I like you'.",
        "Type the most flirty text you can think of.",
        "Send a selfie biting your lip.",
        "Describe what you are wearing right now.",
        "Send a voice note listing 3 of your turn-ons.",
        "Send a photo of your eyes.",
        "Rate my 'vibes' from 1 to 10 and explain why.",
        "Send a voice note singing a romantic song (just one line).",
        "Type a fake breakup text to me.",
        "Send the 5th photo in your gallery (no cheating, even if it's risky).",
        "Tell me the story of your first kiss.",
        "Show me your Ear",
        "Send a screenshot of your home screen.",
        "Send me pic of your eyes",
        "sing a song and send voice note",
        "Send a voice note imitating a celebrity.",
        "Send the last sms you got.",
        "Show your Lower Lip.",
        "Send a voice note of weird laugh.",
        "Send a photo of the view from your window.",
        "Tell me a joke in a voice note.",
        "Bark like a Cat in a voice note.",
        "Send a screenshot of your last Google search.",
        "Send a voice note saying something in a different accent.",
        "Send a pic of your palm",
        "Go to your music player, shuffle, and send the first song that plays.",
        "Send a voice note yelling 'I LOVE THIS BOT!'",
        "Describe what you are wearing right now.",
        "Send a screenshot of your most used emojis.",
        "Record yourself saying a tongue twister-Red Lorry Yellow Lorry three times fast."
    ],

    "wyr": [
        # --- CLASSIC ---
        ("Have infinite money", "Have infinite love"),
        ("Be invisible", "Be able to fly"), 
        ("Always be cold", "Always be hot"),
        ("Have unlimited money", "Have unlimited time"), 
        ("Know how you die", "Know when you die"),
        
        # --- INTERESTING ---
        ("Explore Space", "Explore the Ocean"), 
        ("Talk to animals", "Speak all languages"),
        ("Be a famous movie star", "Be a brilliant scientist"),
        ("Never use social media again", "Never watch movies again"),
        ("Lose your phone", "Lose your wallet"),
        ("Be the smartest person in the room", "Be the funniest person in the room"),
	    ("Be the smartest person in the room", "Be the hottest person in the room"),
        ("Have a rewind button", "Have a pause button"),
	    ("Date someone 10 years older", "Date someone 5 years younger"),
        ("Have amazing sex but no conversation", "Have amazing conversation but bad sex"),
        ("Kiss in the rain", "Kiss by a fireplace"),
        ("Be the heartbreaker", "Have your heart broken"),
        ("Have a partner who is too clingy", "Have a partner who is too distant"),
        ("Forgive a cheater", "Forgive a liar"),
        ("Lights on", "Lights off"),
        ("Morning cuddles", "Late night deep talks"),
        ("Date a famous celebrity", "Date a regular person who adores you"),
        ("Find true love but be poor", "Stay single but be a billionaire"),
        ("Have a one-night stand", "Have a 'friends with benefits' relationship"),
        ("Your partner looks through your phone", "You look through your partner's phone"),
        ("Live in the past", "Live in the future"),
        ("Be able to read minds", "Be able to see the future"),
        ("Give up music", "Give up Video"),
        ("Be feared by all", "Be loved by all"),
        ("Have nosy neighbors", "Have noisy neighbors"),
        ("Be an average person in the present", "Be a King/Queen 1000 years ago"),
        ("Find true love today", "Win the lottery next year"),
        ("Never have to sleep", "Never have to eat"),
        ("Only be able to whisper", "Only be able to shout"),
        ("Be 4'5\" tall", "Be 7'7\" tall"),
        ("Live in a treehouse", "Live in a cave"),
	    ("have universal respect", "unlimited power"),
        ("Have no taste", "Have no smell"),
	    ("Have no partner", "Have 3 partner"),
        ("Always say everything on your mind", "Never be able to speak again"),
	    ("can go to 10 yr in past", "can have 100 millions in present"),
	    ("kiss in public", "kiss in classroom"),
		("Stay virgin life long", "stay single life long"),
		("visit mountains", "visit beach"),
		("Have Piles", "Have AIDS"),
		("hang out in night", "in evening"),
		("sing in public", "dance in public"),
		("watch sunset", "watch sun rise"),
		("prefer overdressed", "under-dressed"),
		("Be Hitler", "Be Kim Jong Un")
    ]
}
