# 📚 GAME CONTENT LIBRARY (PHASE 25 - EXPANDED)

GAME_DATA = {
    "tod_truth": [
        # --- ICEBREAKERS ---
        "What is the last lie you told?", 
        "What is your biggest fear?",
        "Who is your secret crush?",
        "What is your most embarrassing moment?", 
        "Have you ever cheated on a test?",
        "What is the worst gift you ever received?", 
        "What is your biggest regret?",
        "When was the last time you cried?", 
        "What is a secret you've never told anyone?",
        "If you could switch lives with one person, who would it be?",
        "What is a habit you want to break?", 
        "Who is the most annoying person you know?",
        "What is your biggest insecurity?",
        "What is the weirdest dream you've ever had?",
        "Have you ever stalked someone on social media?",
	"Do you have any fake account?",
        "What is the pettiest thing you have ever done?",
        "If you were invisible for a day, what would you do?",
        "What is the worst date you've ever been on?",
        "Have you(someone) ever ghosted someone(you)?",
        "What is one thing you wish you could change about yourself?",
        "Who is the last person you searched on Instagram?",
        "Have you ever broken the law?",
        "What is the most expensive thing you've bought and regretted?",
        "If you had to marry the last person you texted, who would it be?",
        "What is your guilty pleasure?",
        
        # --- DEEP / VIBE CHECK ---
        "Do you believe in soulmates?",
        "What is your biggest deal-breaker in a relationship?",
        "Would you forgive a cheater?",
        "What is the happiest memory of your childhood?",
        "Do you think you are a good person?",
        "What is one thing you want to achieve before you die?",
        "Do you believe in ghosts or aliens?",
	"Saddest moment of your life?",
        "What is the hardest lesson you've had to learn?",
        "If you could apologize to one person from your past, who would it be?",
        "Are you happy with where you are in life right now?",
        "What is your definition of love?",
        "Have you ever fallen in love with a friend?",
        "What is something you are sensitive about?",
        "Do you trust people easily?",
        "What is your biggest fear about the future?",
        # --- FLIRTY & SPICY (User Added) ---
        "What is your love language?",
        "What is your biggest fantasy?",
        "What is one thing you struggle with in relationships?",
        "What was your first impression of me (based on this chat)?",
        "What is the first thing that attracts you to someone?",
        "What usually gets you in a romantic mood?",
        "Have you ever turned down a sexual opportunity and regretted it?",
        "Have you ever hooked up with someone you regret?",
        "At what age did you first learn about sex?",
        "Have you ever sexted?",
        "What is the sexiest song you've ever heard?",
        "What is the sexiest movie scene you've ever watched?",
        "At what age did you watch your first adult video?",
        "Have you ever hit on a random attractive stranger?",
        "Have you ever tried to get back together with an ex?",
        "What is a romantic act that you think is overrated?",
        "What romantic activity do you think is underrated?",
        "Can you fall asleep while cuddling/kissing?",
        "Kissing on the first date: Yay or Nay?",
        "Public Displays of Affection (PDA): Yay or Nay?",
        "What is your favorite body part to be kissed?",
        "Where do you like to leave/get a hickey?",
        "What is the sexiest outfit someone can wear?",
        "How old were you when you had your first kiss?",
        "What do you think is the sexiest part of the opposite gender's body?",
        "What do you think is the sexiest part of YOUR body?"
    ],

    "tod_dare": [
        # --- DIGITAL DARES (Safe for Chat) ---
        "Send a voice note singing 'Happy Birthday' to me.", 
        "Send the last photo which you took (no cheating!).",
        "Send me picture of your nose",
	"Show me your Nails", 
        "Send a sticker that describes your mood right now.",
        "Send me voice note of Count 10 to 1 (quickest you can!)",
        "Send me 5 last used Emoji", 
	"Send a voice note blowing a kiss.",
        "Send a photo of just your lips.",
        "Describe your ideal first date in detail.",
        "Send a voice note whispering 'I like you'.",
        "Type the most flirty text you can think of.",
        "Send a selfie biting your lip.",
        "Describe what you are wearing right now.",
        "Send a voice note listing 3 of your turn-ons.",
        "Send a photo of your eyes.",
        "Rate my 'vibes' from 1 to 10 and explain why.",
        "Send a voice note singing a romantic song (just one line).",
        "Type a fake breakup text to me.",
        "Send the 5th photo in your gallery (no cheating, even if it's risky).",
        "Tell me the story of your first kiss.",
        "Show me your Ear",
        "Send a screenshot of your home screen.",
        "Send me pic of your eyes",
        "sing a song and send voice note",
        "Send a voice note imitating a celebrity.",
        "Send the last sms you got.",
        "Show your Lower Lip.",
        "Send a voice note of weird laugh.",
        "Send a photo of the view from your window.",
        "Tell me a joke in a voice note.",
        "Bark like a Cat in a voice note.",
        "Send a screenshot of your last Google search.",
        "Send a voice note saying something in a different accent.",
        "Send a pic of your palm",
        "Go to your music player, shuffle, and send the first song that plays.",
        "Send a voice note yelling 'I LOVE THIS BOT!'",
        "Describe what you are wearing right now.",
        "Send a screenshot of your most used emojis.",
        "Record yourself saying a tongue twister-Red Lorry Yellow Lorry three times fast."
    ],

    "wyr": [
        # --- CLASSIC ---
        ("Have infinite money", "Have infinite love"),
        ("Be invisible", "Be able to fly"), 
        ("Always be cold", "Always be hot"),
        ("Have unlimited money", "Have unlimited time"), 
        ("Know how you die", "Know when you die"),
        
        # --- INTERESTING ---
        ("Explore Space", "Explore the Ocean"), 
        ("Talk to animals", "Speak all languages"),
        ("Be a famous movie star", "Be a brilliant scientist"),
        ("Never use social media again", "Never watch movies again"),
        ("Lose your phone", "Lose your wallet"),
        ("Be the smartest person in the room", "Be the funniest person in the room"),
	("Be the smartest person in the room", "Be the hottest person in the room"),
        ("Have a rewind button", "Have a pause button"),
	("Date someone 10 years older", "Date someone 5 years younger"),
        ("Have amazing sex but no conversation", "Have amazing conversation but bad sex"),
        ("Kiss in the rain", "Kiss by a fireplace"),
        ("Be the heartbreaker", "Have your heart broken"),
        ("Have a partner who is too clingy", "Have a partner who is too distant"),
        ("Forgive a cheater", "Forgive a liar"),
        ("Lights on", "Lights off"),
        ("Morning cuddles", "Late night deep talks"),
        ("Date a famous celebrity", "Date a regular person who adores you"),
        ("Find true love but be poor", "Stay single but be a billionaire"),
        ("Have a one-night stand", "Have a 'friends with benefits' relationship"),
        ("Your partner looks through your phone", "You look through your partner's phone"),
        ("Live in the past", "Live in the future"),
        ("Be able to read minds", "Be able to see the future"),
        ("Give up music", "Give up Video"),
        ("Be feared by all", "Be loved by all"),
        ("Have nosy neighbors", "Have noisy neighbors"),
        ("Be an average person in the present", "Be a King/Queen 1000 years ago"),
        ("Find true love today", "Win the lottery next year"),
        ("Never have to sleep", "Never have to eat"),
        ("Only be able to whisper", "Only be able to shout"),
        ("Be 4'5\" tall", "Be 7'7\" tall"),
        ("Live in a treehouse", "Live in a cave"),
	("have universal respect", "unlimited power"),
        ("Have no taste", "Have no smell"),
	("Have no partner", "Have 3 partner"),
        ("Always say everything on your mind", "Never be able to speak again"),
	("can go to 10 yr in past", "can have 100 millions in present"),
	("kiss in public", "kiss in classroom"),
	("Stay virgin life long", "stay single life long"),
	("visit mountains", "visit beach"),
	("Have Piles", "Have AIDS"),
	("hang out in night", "in evening"),
	("sing in public", "dance in public"),
	("watch sunset", "watch sun rise"),
	("prefer overdressed", "under-dressed"),
	("Be Jiws in front of Hitler", "Be American in front of Osama ")
    ],

"tod_truth_spicy": [
        # === YOUR ORIGINAL ONES (kept) ===
        # ... paste your existing list here ...

        # === NEW VIRGIN-FRIENDLY SPICY TRUTHS ===
        "What's the naughtiest dream you've ever had about someone?",
        "Have you ever had a wet dream? What happened in it?",
        "What's your biggest sexual fantasy right now?",
        "How often do you masturbate in a week?",
        "What's your favorite way to touch yourself?",
        "Have you ever touched yourself while thinking about a stranger or someone you just met?",
        "What's the hottest thing you've ever imagined doing with someone?",
        "At what age did you first touch yourself sexually?",
        "Have you ever watched porn? What's your favorite type?",
        "What's the dirtiest thought you've had about someone you barely know?",
        "Do you get wet/hard easily when you think about kissing or touching someone?",
        "What's one thing you've never done but really want to try sexually?",
        "Have you ever sexted or sent flirty dirty messages?",
        "What's your favorite body part on the opposite sex to stare at?",
        "How long was your longest make-out session?",
        "Have you ever been so horny you couldn't sleep?",
        "What's the most embarrassing thing that happened while you were touching yourself?",
        "Do you moan or stay quiet when you're pleasuring yourself?",
        "What's the sexiest outfit you've imagined wearing for someone?",
        "Have you ever imagined losing your virginity to a stranger?",
        "What's your go-to fantasy when you're alone and horny?",
        "Do you like the idea of being watched while touching yourself?",
        "What's one kink or fantasy you have that you're shy about?",
        "Have you ever kissed someone and felt yourself getting really turned on?",
        "What's the hottest compliment you've ever received about your body?",
        "Do you prefer slow teasing or fast and intense when imagining sex?",
        "Have you ever role-played in your head during masturbation?",
        "What's the longest you've stayed edged without finishing?",
        "Do you like the idea of teasing someone until they're desperate?",
        "What's something sexual you've seen in porn that you want to try one day?"
    ],

    "tod_dare_spicy": [


        # === NEW VIRGIN-FRIENDLY SPICY DARES ===
        "Send a voice note moaning softly like you're really turned on.",
        "Describe in detail how you would kiss me if we were alone right now.",
        "Send a selfie biting your lip and looking at the camera seductively.",
        "Type the dirtiest, flirtiest text you can imagine sending me right now.",
        "Send a voice note whispering exactly what turns you on the most.",
        "Describe what you're wearing right now... in the sexiest way possible.",
        "Send a photo of just your neck and collarbone area.",
        "Voice note: Say my name in the hottest, breathiest voice you can.",
        "Tell me step-by-step what you would do with your hands if we were kissing.",
        "Send a voice note breathing heavily as if we're making out.",
        "Describe your favorite fantasy of how you want to lose your virginity.",
        "Send a selfie pulling your shirt/collar down just a little (show some skin).",
        "Voice note: Tell me where you would want me to kiss you first.",
        "Show me a photo of your lips really close up.",
        "Type out how you imagine our first kiss would feel.",
        "Send a voice note pretending we're having a very flirty phone-sex tease.",
        "Describe exactly how you touch yourself when you're horny.",
        "Send a photo of your thighs or legs (clothed is fine, make it teasing).",
        "Voice note: Say 'I want you' in the most desperate, sexy way.",
        "Tell me your favorite spot on your body that you love being touched.",
        "Do a slow, teasing voice note describing what you would do to my body with your hands.",
        "Send a screenshot of the last spicy search you did (you can blur parts).",
        "Voice note: Count from 10 to 1 while sounding more and more turned on.",
        "Describe the underwear you're wearing right now in full detail.",
        "Send a voice note of you sucking on your finger slowly and seductively.",
        "Tell me the sluttiest fantasy you've had about a stranger.",
        "Show me your tongue in a very naughty way (photo or short video).",
        "Voice note: Whisper what you would do if I was right there with you right now."
    ],

    "wyr_spicy": [

        # === NEW VIRGIN SPICY WOULD YOU RATHER ===
        ("Lose your virginity to someone you love", "Lose your virginity to a hot stranger"),
        ("Have your first time be slow and romantic", "Have your first time be rough and passionate"),
        ("Kiss for hours", "Make out and touch each other everywhere above the waist"),
        ("Be completely naked with someone but no touching", "Touch and tease each other but stay fully clothed"),
        ("Have amazing foreplay but no penetration", "Have penetration but very little foreplay"),
        ("Moan loudly during your first time", "Stay completely silent"),
        ("Lose your virginity with lights on", "Lose your virginity in total darkness"),
        ("Your partner teases you for a long time before anything happens", "Go straight into it"),
        ("Have your first kiss turn into making out immediately", "Have a slow, shy first kiss"),
        ("Watch porn together before doing anything", "Talk dirty to each other before touching"),
        ("Be the one who takes control on your first time", "Let your partner take full control"),
        ("Have your first time in a bed", "Have your first time somewhere risky like a car or outside"),
        ("Get lots of hickeys during your first time", "Leave lots of hickeys on your partner"),
        ("Have slow sensual touching all over", "Have fast desperate touching"),
        ("Lose your virginity while making eye contact the whole time", "Lose your virginity while blindfolded"),
        ("Be eaten out / given a handjob as your first sexual act", "Give oral / a handjob as your first sexual act"),
        ("Have your first time last a very long time", "Have your first time be quick and intense"),
        ("Tease each other with clothes on for hours", "Get naked immediately"),
        ("Have your first orgasm with a partner", "Have your first orgasm alone while thinking about them"),
        ("Kiss and touch in public where you might get caught", "Kiss and touch privately but very intensely"),
        ("Have your partner describe exactly what they want to do to you", "Describe exactly what you want to do to them"),
        ("Be spanked lightly during your first time", "Spank your partner lightly"),
        ("Have lots of dirty talk", "Have almost no talking, just heavy breathing and moaning"),
        ("Lose your virginity to someone experienced", "Lose your virginity to another virgin"),
        ("Have morning sex as your first time", "Have late night sex as your first time"),
        ("Be tied up gently for your first time", "Tie your partner up gently"),
        ("Have your first time while slightly drunk", "Have your first time completely sober"),
        ("Focus only on kissing and touching above the waist", "Focus on touching below the waist too"),
        ("Have your first time with music playing", "Have your first time in complete silence")
    ]

}
